### ISSUE TITLE
questions regarding MPC cost function

### ISSUE THREAD

**Issue by yifan96** [nocholasrift/mpc_trajectory_tracking#2]
Hi,
I've been playing with your trajectory_tracking code, very nice work.\
I have a few questions regarding the setup of the controller.
1. The objective of the mpc_traj_tracking is to minimize the cross-track error. Why do you penalize x, y deviations in the cost function, are they redundant? 
2. I notice there is a difference of range for penalizing linear velocity and angular velocity. why is that?
![image](https://github.com/nocholasrift/mpc_trajectory_tracking/assets/63547586/9f760460-53af-4de7-a1b1-0e9b570e747b)
3. Is it more precise to have this "limit formation" of kinematics?
![image](https://github.com/nocholasrift/mpc_trajectory_tracking/assets/63547586/7a806ff3-dbe1-458d-af9a-5e8f4fbeea7b)

**Comment by nocholasrift** [comment]
Hi there, glad you are enjoying the package! 

1. I actually added in the x,y deviation penalty specifically because I found using only cross track error and theta error to not be enough for high quality tracking. You can set those weights to 0 and see if they result in any performance degradation for you. In my experience, having those terms in help tremendously with tracking performance.
2. Thank you for pointing that out! That is actually a bug that I fixed a while back in another private MPC repo of mine, but forgot to change it here! The linvel and angvel are both inputs to the system, and thus there are only _mpc_steps-1 of those variables. The linvel cost term should be in that second for loop or broken out into it's own for loop from i=0 to mpc_steps -1. I will be releasing a large MPC package hopefully be the end of the summer with small bug fixes like this, along with other additional features like more models and solvers, so stay tuned for that! (This is also why I haven't updated this repository in a while)
3. I was trying to be more precise by using the discrete unicycle model, but I honestly found no performance benefit compared to the continuous time model. And it probably is slowing down the optimization to have that branch condition, so if you want, feel free to just use the continuous model :)

**Comment by nocholasrift** [comment]
Going to close this for now but feel free to reopen if anything comes up
